// Declare products array globally
const products = [
    {
        id: 1,
        name: " 6 PACK GIFT UNISEX SET - Chaussettes - white",
        description: "Comfortable cotton socks",
        price: 0.49,
        image: "front/images/O1CN01g8JIee1xdwFISVtVb_!!2206448856467-0-cib.jpg",
        image1: "front/images/O1CN01cuAwxa1xdwFEFLeaC_!!2206448856467-0-cib.jpg",
        image2: "front/images/O1CN015U8a3u1xdwFEFKa3h_!!2206448856467-0-cib.jpg",
        image3: "front/images/O1CN01u1ijh61xdwFAXPaqZ_!!2206448856467-0-cib.jpg",
        category:"women",
        //url:https://detail.1688.com/offer/726422540673.html?_t=1729276832164&spm=a2615.7691456.co_0_0_wangpu_score_0_0_0_0_0_0_0000_1.0
        color: "1",
        detailPage: "product-detail.html",
        colors: ["Red", "Blux", "Green"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 2,
        name: "Women's Woollen Stockings 2024 Autumn/Winter Thickening Warm Bow Embroidery Warm Japanese College Wind Heap Stockings",
        description: "Comfortable cotton socks",
        price: 18.00,
        image: "front/images/PGW2.jpg",
        image1: "front/images/PB2.jpg",
        image2: "front/images/PDG2.jpg",
        image3: "front/images/PA2.jpg",
        image4: "front/images/PP2.jpg",
        image5: "front/images/PW2.jpg",
        color: "unique",
        detailPage: "product-detail.html",
        colors: ["Red", "Blux", "Green"],
        sizes: ["S", "M", "L"]
    },
    
      {
        id: 3,
        name: "Cotton socks bow",
        description: "Comfortable cotton socks",
        price: 6.99,
        image: "front/images/DP bow 1.jpg",
        image1: "front/images/DP bow 2.jpg",
        image2: "front/images/DP bow 3.jpg",
        image2: "front/images/DP bow 4.jpg",
        image2: "front/images/DP bow 5.jpg",
        color: "unique",
        detailPage: "product-detail.html",
        colors: ["Red", "Blux", "Green"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 4,
        name: "Stripe AB embroidered puppy socks children double-stitch cotton medium stockings European goods niche wear stacks of stockings",
        description: "Comfortable cotton socks",
        price: 6.99,
        image: "front/images/FP striped puppy1.jpg",
        image1: "front/images/FP striped puppy2.jpg",
        image2: "front/images/FP striped puppy3.jpg",
        image2: "front/images/FP striped puppy4.jpg",
        image2: "front/images/FP striped puppy5.jpg",
        color: "unique",
        detailPage: "product-detail.html",
        colors: ["Red", "Blux", "Green"],
        sizes: ["S", "M", "L"]
    },
    
    {
        id: 5,
        name: "Small fragrance wood ear bow socks children Autumn and winter new products ins tide day sweet wooden ear jk stack stockings",
        description: "Comfortable cotton socks",
        price: 8.99,
        image: "front/images/BPbow 1.jpg",
        image1: "front/images/BPbow 2.jpg",
        image2: "front/images/BPbow 3.jpg",
        color: "unique",
        detailPage: "product-detail.html",
        colors: ["Red", "Blux", "Green"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 6,
        name: "Korean Version ins Relaxation Feeling Heap Stacks of Stockings Followed by Cloth Label Thick Thread Knitted Vertical Stripes Spring and Autumn Solid Color Calf Stockings",
        description: "Comfortable cotton socks",
        price: 5.89,
        image: "front/images/CPABletter face 1.jpg",
        image1: "front/images/CPABletter face 2.jpg",
        image2: "front/images/CPABletter face 3.jpg",
         image3: "front/images/CPABletter face 4.jpg",
         image4: "front/images/CPABletter face 5.jpg",
         image5: "front/images/CPABletter face 6.jpg",
        color: "unique",
        detailPage: "product-detail.html",
        colors: ["Red", "Blux", "Green"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 7,
        name: "PACK 5 Autumn/Winter Coffee Central Socks Women's Stripes Women's Socks",
        description: "Comfortable cotton socks",
        price: 29.99,
        image: "front/images/PA4.jpg",
        image1: "front/images/PB4.jpg",
        image2: "front/images/PH4.jpg",
        image3: "front/images/PM4.jpg",
        image4: "front/images/PLG4.jpg",
        image5: "front/images/PP4.jpg",
        image6: "front/images/PZ4.jpg",
        color: "unique",
        detailPage: "product-detail.html",
        colors: ["Red", "Blux", "Green"],
        sizes: ["S", "M", "L"]
    },
  
    {
        id: 8,
        name: "Retro little bee embroidered double stitch stack socks children Ankola Red Central Stockings miu Series Trend Red Stockings",
        description: "Comfortable cotton socks",
        price: 12.99,
        image: "front/images/EP bee1.jpg",
        image1: "front/images/EP bee2.jpg",
        image2: "front/images/EP bee3.jpg",
        image3: "front/images/EP bee4.jpg",
        image4: "front/images/EP bee5.jpg",
        color: "unique",
        detailPage: "product-detail.html",
        colors: ["Red", "Blux", "Green"],
        sizes: ["S", "M", "L"]
    },
    
    {
        id: 9,
        name: "Autumn and Winter Coarse Line Stockings Children Korean Polished Color Ideas Yarn Cashmere Thickened and Warm Wool",
        description: "Comfortable cotton socks",
        price: 6.99,
        image: "front/images/PL3.jpg",
        image1: "front/images/PGL3.jpg",
        image2: "front/images/PG3.jpg",
        color: "unique",
        detailPage: "product-detail.html",
        colors: ["Red", "Blux", "Green"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 10,
        name: "Cute Cartoon Cubs Embroidered Warm Socks Kids Korean Version Trend Two Bars Socks",
        description: "Comfortable cotton socks",
        price: 12.99,
        image: "front/images/GP bear 2.jpg",
        image1: "front/images/GP bear 1.jpg",
        image2: "front/images/GP bear 3.jpg",
        image3: "front/images/GP bear 4.jpg",
        image4: "front/images/GP bear 5.jpg",
        image5: "front/images/GP bear 6.jpg",
        color: "unique",
        detailPage: "product-detail.html",
        colors: ["Red", "Blux", "Green"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 11,
        name: "Cashmere socks soft skin warm",
        description: "Comfortable cotton socks",
        price: 11.99,
        image: "front/images/IP natural 4.jpg",
        image1: "front/images/IP natural 1.jpg",
        image2: "front/images/IP natural 2.jpg",
        image3: "front/images/IP natural 3.jpg",
        image4: "front/images/IP natural 4.jpg",
        image5: "front/images/IP natural 5.jpg",
        image6: "front/images/IP natural 6.jpg",
        color: "unique",
        detailPage: "product-detail.html",
        colors: ["Red", "Blux", "Green"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 11,
        name: "Cartoon Letter Heat Storage Heat Protection Ideas Yarn Wool Stockings Merad Puppies Cute Medium Stockings",
        description: "Comfortable cotton socks",
        price: 7.99,
        image: "front/images/JP animal 2.jpg",
        image1: "front/images/JP animal 1.jpg",
        image2: "front/images/JP animal 3.jpg",
        image3: "front/images/JP animal 4.jpg",
        image4: "front/images/JP animal 5.jpg",
        image5: "front/images/JP animal 6.jpg",
        image5: "front/images/JP animal 7.jpg",
        color: "unique",
        detailPage: "product-detail.html",
        colors: ["Red", "Blux", "Green"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 12,
        name: "Cute Cartoon Warm Socks",
        description: "Comfortable cotton socks",
        price: 6.99,
        image: "front/images/KP animal 1.jpg",
        image1: "front/images/KP animal 2.jpg",
        image2: "front/images/KP animal 3.jpg",
        image3: "front/images/KP animal 4.jpg",
        image4: "front/images/KP animal 5.jpg",
        color: "unique",
        detailPage: "product-detail.html",
        colors: ["Red", "Blux", "Green"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 13,
        name: "Autumn and winter puppies in sock stripes flip side cartoon dachshund dogs vertical stack stockings cute niche four-season stockings",
        description: "Comfortable cotton socks",
        price: 6.99,
        image: "front/images/LP animal 1.jpg",
        image1: "front/images/LP animal 2.jpg",
        image2: "front/images/LP animal 3.jpg",
        image3: "front/images/LP animal 4.jpg",
        color: "unique",
        detailPage: "product-detail.html",
        colors: ["Red", "Blux", "Green"],
        sizes: ["S", "M", "L"]
    }
];




